### ISSUE TITLE
Adding current sensing for each motor with Wemos D1 R32

### ISSUE THREAD

**Issue by RoboKez** [simplefoc/Arduino-FOC-balancer#2]
This is a great project! I have successfully replicated it with the same hardware (except I used magnetic encoders). I'm now looking to add current sensing. 

I have the same 2.0.3 shield pinout configuration you used and the same Wemos D1 R32. However A1 and A2 are not defined for the wemos D1 R32 when the board is set to the "WEMOS D1 MINI ESP32" in the Arduino IDE. Do you know what pins I should define as A1 and A2?

Thanks again

Kez

**Comment by askuric** [comment]
Hey @RoboKez,
I'm happy to hear that!
![image](https://user-images.githubusercontent.com/36178713/128598325-a5647603-d8bb-4156-b76a-55e7306ab197.png)

As far as I know, none of the Arduino analog pins should be defined for the esp32 boards. 

The pinout is in most cases printed on the board weemos board, you can verify if it is the same on the image.
If it is your analog pons should be:
- `A0` - 2
- `A1` - 4
- `A2` - 35
- `A3` - 34
I hope it helps 🙂

**Comment by RoboKez** [comment]
Great thanks @askuric! Do I want to include **current_sense.gain_b *=-1;** for the v2.0.3 sheild? Also I noticed you set the voltage power supply to 12v in the video but change it to 8v on github. Should it be 8 as the 8v regulator is enabled?

**Comment by askuric** [comment]
Hey Kez,
The `current_sense.gain_b =-1;` you can includebut you do not have to, since the `initFOC` will do the current sensor alignment itself and it should find this automatically.
But since you know this beforehand you can avoid current sense alignment by setting the:
```cpp
....
current_sense.gain_b =-1;
// skip alignment procedure
current_sense.skip_align = true;
motor.initFOC()
```

In the git code I've set it the power supply to 8V only because I've used 2 cell battery latter on; instead of 3cell one as in the video.
8V regulator does not have anything to do with this, 8V go only to the VIN port of the microcontroller and the full power supply voltage is powering the motor.

**Comment by RoboKez** [comment]
Great, that makes sense. Thanks again @askuric! 👍
