### ISSUE TITLE
pid tuning approach

### ISSUE THREAD

**Issue by RoboKez** [simplefoc/Arduino-FOC-balancer#3]
Hi @askuric!

This is a great stable system, what approach did you take to tuning the gains? Also on a separate note their is a minor capital error in line 9 of the balancer_pinouts.h,  MOT1_En should be MOT1_EN

Thanks again,

Kez

**Comment by askuric** [comment]
Hey @RoboKez !
Thanks for the message and I am sorry that I did not respond earlier. 
I've updated the typo in the variable naming of the motor 1 enable pin. 

Regarding the tuning procedure, it is a really good question. I've somewhat hinted it once in the community post about this robot, I hope you'll find it useful. 😄 
https://community.simplefoc.com/t/self-balancing-robot/343/24?u=antun_skuric

But basically, I was not trying to model this robot at all, all the PIDs are hand-tuned using the described procedure. The model of the robot would not be that much more difficult to find, since the cad model is pretty precise and all the masses of the components can be measured pretty well. And you could even approximate the BLDC motor with the DC motor dynamics. And once you have your dynamical system you can find an optimal PID stabilization controller based on different stability criteria as Hurwitz or similar. But I did not go there for this project. 😄 

For the motion control it becomes a bit more complicated, since you need to control the balancer angle to produce the desired movement and to stay stable. And as the motion control (velocity control) cannot be separated from the stabilization control then there are no really simple control engineering procedures to solve this. So the easiest way is to hand tune it, because the dynamics of these BLDC motors are awesome and even with suboptimal PID parameters the segway is very dynamic and stable. 😄  

I hope it helps, I am not sure if I've answered your question though. 😄

**Comment by RoboKez** [comment]
Hi @askuric ,

Thanks for the response and the post was very helpful! I'm really enjoying th SimpleFOC library awesome work!

Cheers,
Kez
